function safeText(value){return typeof value==="string"?value.trim():""}function getBody(req){if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return {}}}return req.body||{}}function styleInstruction(style){if(style==="kort")return "Skriv kort og presist. Fjern unødvendig tekst, men behold viktige fakta.";if(style==="teknisk")return "Skriv som en teknisk rapport til kunde. Bruk faglig presist språk, men fortsatt forståelig norsk.";return "Skriv kundevennlig, profesjonelt, rolig og tydelig."}function emptyFieldInstruction(status,area,sectionTitle){if(status==="Ingen avvik")return `Feltet er tomt. Lag et nøytralt forslag for ${sectionTitle} basert på at område er "${area}" og status er "Ingen avvik". Du kan skrive at det ikke er observert kritiske avvik, men ikke legg til konkrete tester, målinger eller detaljer som ikke er oppgitt.`;if(status==="Ikke utført")return `Feltet er tomt. Lag et kort og ryddig forslag for ${sectionTitle} basert på at dette ikke er utført. Ikke finn på årsak.`;if(status==="Krever oppfølging"||status==="JIRA-sak opprettet")return `Feltet er tomt. Lag et forslag for ${sectionTitle} som sier at forholdet krever videre oppfølging. Ikke finn på saksnummer eller konkrete tiltak som ikke er oppgitt.`;return `Feltet er tomt. Lag et generelt og forsiktig forslag for ${sectionTitle} basert på valgt system og område. Ikke påstå at konkrete kontroller er utført hvis det ikke står i teksten.`}function buildSinglePrompt(data){const sectionTitle=safeText(data.sectionTitle);const sectionText=safeText(data.sectionText);const system=safeText(data.system);const area=safeText(data.area);const status=safeText(data.status);const contact=safeText(data.contact);const rules=[styleInstruction(data.style),"Skriv på norsk bokmål.","Returner kun teksten som skal stå i dette ene rapportfeltet. Ikke ta med overskrift.","Ikke skriv forklaring før eller etter.","Ikke si at du er en AI.","Behold relevante saksnummer, romnummer, systemnavn og tekniske detaljer.",data.noNewFacts?"Ikke legg til ny informasjon som ikke står i rapportgrunnlaget. Unntak: hvis feltet er tomt kan du lage en forsiktig standardformulering basert på valgte nedtrekksmenyer.":"",data.keepTechnical?"Behold tekniske begreper som NISM, AWA View, Unite, IP-DECT, Myco, logg, backup, fjerndrift og saksnummer når de er relevante.":"",data.noSensitive?"Ikke ta med sensitive personopplysninger eller helseopplysninger. Bruk heller kunde, beboer, romnummer eller enhet der det passer.":"","Rett skrivefeil og gjør teksten egnet for en kunderapport.","Hvis råteksten er uklar, gjør den mer ryddig uten å endre betydningen.","Hvis det står at noe ikke er utført, ikke skriv at det er utført.","Hvis det står at kunde er fornøyd, kan det formuleres profesjonelt uten å overdrive."].filter(Boolean).join("\n");const fieldInstruction=sectionText?"Omformuler råteksten bedre. Ikke endre fakta.":emptyFieldInstruction(status,area,sectionTitle);return `${rules}

KONTEKST
Rapporttype: Årlig kontroll / kunderapport
Rapportfelt: ${sectionTitle}
Kundesamtale med: ${contact||"Ikke oppgitt"}
System: ${system||"Ikke oppgitt"}
Område: ${area||"Ikke oppgitt"}
Status: ${status||"Ikke valgt"}

OPPGAVE
${fieldInstruction}

RÅTEKST FRA TEKNIKER
${sectionText||"(tomt felt)"}`}module.exports=async function handler(req,res){if(req.method!=="POST")return res.status(405).json({error:"Kun POST er støttet."});if(!process.env.GITHUB_TOKEN)return res.status(500).json({error:"GITHUB_TOKEN mangler i Vercel Environment Variables."});try{const data=getBody(req);if(data.mode!=="single")return res.status(400).json({error:"Denne versjonen støtter feltvis generering. Send mode: single."});const prompt=buildSinglePrompt(data);const model=process.env.GITHUB_MODEL||"openai/gpt-4.1-mini";const ghResponse=await fetch("https://models.github.ai/inference/chat/completions",{method:"POST",headers:{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,"Content-Type":"application/json","X-GitHub-Api-Version":"2022-11-28"},body:JSON.stringify({model,messages:[{role:"system",content:"Du hjelper norske teknikere med å skrive korte, kundevennlige og presise rapportfelt etter årlig kontroll. Du skal være faktabasert og ikke finne på detaljer."},{role:"user",content:prompt}],temperature:.2,max_tokens:700})});const result=await ghResponse.json();if(!ghResponse.ok)return res.status(ghResponse.status).json({error:result?.message||result?.error?.message||"Feil fra GitHub Models."});const text=result?.choices?.[0]?.message?.content||"Ingen tekst ble generert.";return res.status(200).json({text:text.trim()})}catch(error){return res.status(500).json({error:error?.message||"Ukjent feil ved formulering."})}};
